name: ShopAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar la clave SSH decodificando desde Base64
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          # Toma el texto en Base64 de tus secretos, lo decodifica y lo guarda en un archivo físico limpio
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Levanta el agente SSH nativo de Linux y registra la clave recién creada
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          
          # Guarda las variables del agente en el entorno de GitHub para los siguientes pasos
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

      # 3. Agregar la IP de tu VPS a los hosts conocidos
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # 4. Probar que la conexión SSH funcione correctamente
      - name: Test SSH
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "echo SSH OK"

      # 5. Ejecutar los comandos de despliegue dentro de tu VPS
      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}

            git pull origin main

            uv sync

            uv run python manage.py migrate

            uv run python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn-shopapi
            sudo systemctl restart nginx
          EOF